- type: replace
  path: /azs/name=z1/cloud_properties
  value:
    availability_zone: ((iaas.availability_zone))

- type: replace
  path: /vm_types/name=default/cloud_properties
  value:
    instance_type: t2.medium
    ephemeral_disk: {size: 25_000}

- type: replace
  path: /vm_types/name=large/cloud_properties
  value:
    instance_type: t2.large
    ephemeral_disk: {size: 50_000}

- type: replace
  path: /networks/name=public/subnets/0/range
  value: ((iaas.public_subnet_cidr))
- type: replace
  path: /networks/name=public/subnets/0/gateway
  value: ((iaas.public_subnet_gateway))
- type: replace
  path: /networks/name=public/subnets/0/cloud_properties
  value:
    subnet: ((iaas.public_subnet_id))

- type: replace
  path: /networks/name=private/subnets/0/range
  value: ((iaas.private_subnet_cidr))
- type: replace
  path: /networks/name=private/subnets/0/gateway
  value: ((iaas.private_subnet_gateway))
- type: replace
  path: /networks/name=private/subnets/0/cloud_properties
  value:
    subnet: ((iaas.private_subnet_id))

- type: replace
  path: /networks/name=internal/subnets/0/range
  value: ((iaas.internal_subnet_cidr))
- type: replace
  path: /networks/name=internal/subnets/0/gateway
  value: ((iaas.internal_subnet_gateway))
- type: replace
  path: /networks/name=internal/subnets/0/cloud_properties
  value:
    subnet: ((iaas.internal_subnet_id))
